### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by Hetalvgandhi** [duhaime/cluster-semantic-vectors#1]
Hello Sir,
Thank you Sir, for sharing code for 'cluster-semantic-vectors'

When using this code with Word-vectors generated for Hindi corpus using file Hindi_word_vec_dd.py, and using it for clustering them using cluster_vectors.py, I came across this error: ValueError: Expected 2D array, got 1D array instead: array=[]. Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Can you please help to find where I am making some mistake?

[dd.zip](https://github.com/duhaime/cluster-semantic-vectors/files/2723004/dd.zip)

**Comment by duhaime** [comment]
Thanks for your note @Hetalvgandhi and sorry for your troubles.

In this case, I'd offer a slight tweak to the way you create the word vectors. The updated script could look like this:

```
# -*- coding: utf-8 -*-
'''
Created on Sat Nov 24 17:35:33 2018

@author: HVG
'''
import pandas as pd
from gensim.models import Word2Vec

def clean(s):
  return [w.strip(",.'!?:;()\'") for w in s]

# specify dimensionality of vectors and input file
vec_size = 50

# create the dataframe for the word vectors
df_list = []
f = open('ALL_SENTENCES1.txt','r', encoding='utf8')
for line_idx, line in enumerate(f.readlines()):
  if line_idx < 100: # remove this line and dedent the following to process all of your data
    df_list.append(line)
df = pd.DataFrame(df_list, columns=['text'])

corpus_text = ''.join(df[:]['text'])
sentences = corpus_text.split('\n')
sentences = [line.lower().split(' ') for line in sentences]
sentences = [clean(s) for s in sentences if len(s) > 0]
model = Word2Vec(sentences, size=vec_size, min_count=1)

# one can retrieve all of the vectors from a trained model as follows:
X = model[model.wv.vocab] # thanks for this! ;)

# grok some sample vectors
word_vectors = model.wv
print(word_vectors['दुरुपयोग'])
print(word_vectors['बार'])
print(word_vectors['कंपनी'])

# persist the model
model.save('new-output.model')
```

The key here is the simple persistence method, which comes from the [gensim docs](https://radimrehurek.com/gensim/models/word2vec.html).

Once you do that, you can load the persisted model with:

```
from gensim.models import Word2Vec
model = Word2Vec.load('new-output.model')
```

Then one can iterate over the model vocabulary and get the corresponding vectors with the methods you included in your model generation script:

```
for word in model.wv.vocab:
  vec = model.wv[ word ]
```

So to given this, we just need to update the `cluster_vectors.py` script so as to gather this list of word vectors and tokens, something like:

```
from __future__ import division
from gensim.models import Word2Vec
from sklearn.cluster import MiniBatchKMeans
from numbers import Number
import sys, codecs, numpy, json

class autovivify_list(dict):
  '''Pickleable class to replicate the functionality of collections.defaultdict'''
  def __missing__(self, key):
    value = self[key] = []
    return value

  def __add__(self, x):
    '''Override addition for numeric types when self is empty'''
    if not self and isinstance(x, Number):
      return x
    raise ValueError

  def __sub__(self, x):
    '''Also provide subtraction method'''
    if not self and isinstance(x, Number):
      return -1 * x
    raise ValueError

def build_word_vector_matrix(gensim_model, n_words=10000):
  '''
  Iterate over the word vectors created with Gensim
  and return its vectors and labels as arrays
  '''
  numpy_arrays = []
  labels_array = []
  model = Word2Vec.load(gensim_model)
  for word in model.wv.vocab:
    vec = model.wv[word]
    # add the values to the arrays
    numpy_arrays.append(vec)
    labels_array.append(word)
  return numpy.array( numpy_arrays ), labels_array

def find_word_clusters(labels_array, cluster_labels):
  '''Read in the labels array and clusters label and return the set of words in each cluster'''
  cluster_to_words = autovivify_list()
  for c, i in enumerate(cluster_labels):
    cluster_to_words[ str(i) ].append( labels_array[c] )
  return cluster_to_words

def get_clusters_from_file(input_vector_file, n_words, reduction_factor):
  n_words           = int(n_words)
  reduction_factor  = float(reduction_factor)
  clusters_to_make  = int( n_words * reduction_factor )
  df, labels_array  = build_word_vector_matrix(input_vector_file, n_words)
  kmeans_model      = MiniBatchKMeans(init='k-means++', n_clusters=clusters_to_make)
  kmeans_model.fit(df)
  cluster_labels    = kmeans_model.labels_
  cluster_inertia   = kmeans_model.inertia_
  cluster_to_words  = find_word_clusters(labels_array, cluster_labels)
  with open("absa_clusters_" + str(n_words) + "_words.json",'w') as json_out:
    json.dump(cluster_to_words, json_out)
  for c in cluster_to_words:
    print('key: {} Val: {} '.format(c, cluster_to_words[c]))
    print("\n")
  return(cluster_to_words)

# config
n_words = 100
vector_size = 50
reduction_factor  = 0.2
input_vector_file = 'new-output.model'

# read the input vector file
cluster_to_words = get_clusters_from_file(input_vector_file, n_words, reduction_factor)
```

Does that make sense? If not please just say the word and I'll be happy to try and help...

**Comment by Hetalvgandhi** [comment]
Thanks a lot @duhaime for your invaluable help.
It works very fine.
Actually, the main problem was with the way I was saving the model and then trying to build the word vectors using 'build_word_vector_matrix' method.
I came to know it.
We can't use codecs with encoding specified over here.... It becomes complex..... no?

Also Sir, it would be grateful if you can suggest value for 'reduction_factor' for a vocabulary of more than 10,000 words if we want to use the cluster_id's as features for each word to be used for labeling using Conditional Random Field (CRF).
OR Experimentation would be only solution..

**Comment by duhaime** [comment]
Thanks for your note @Hetalvgandhi. I'm glad this helps.

Right, you shouldn't need to specify the encoding when persisting the model. If you just use the gensim persistence methods all should be well :)

Yes, I would experiment to determine how much reduction will make sense. I'd need to know more about the goal of the CRF model to have any intuitions, but you know your problem domain, so hopefully should be able to try and find some decent parameters for the reduction.

**Comment by Hetalvgandhi** [comment]
Thanks a lot for immediate reply.
Yes, taking up the domain content, and processing it, I would try out for different reduction factor values.

**Comment by duhaime** [comment]
That sounds great @Hetalvgandhi! If you feel this problem is resolved, please feel free to close the issue. If you hit other snags, feel free to reach out or follow up any time...

**Comment by Hetalvgandhi** [comment]
The clustering has no issues.
Thanks a lot @duhaime for your kind co-operation....
